### ISSUE TITLE
[T1P2] Hasta que punto se puede interpretar el espacio M de mensajes?

### ISSUE THREAD

**Issue by Zetaku1** [IIC3253/2023#10]
Hola, me gustaría saber si podemos asumir ciertas cosas en nuestro esquema para el espacio de mensajes dado.

Por ejemplo el hecho de que en binario los mensajes 01, 001, 00001 equivalen al mismo valor a pesar de tener largos distintos.

En el espacio de mensajes dado, se puede asumir algo similar? Es decir asumir que 01, 001, 00001 equivalen al mismo mensaje?

**Comment by marceloarenassaavedra** [comment]
En la pregunta 2 los espacios de mensajes, claves y textos cifrados están compuestos por strings sobre el alfabeto ``{0, 1}``. En este sentido, los strings ``01``, ``001``, ``00001`` son distintos, y deben ser tratados como tales (no puedes suponer que representan el mismo número codificado en binario).

Saludos!
