### ISSUE TITLE
[T1P4] Duda existe función de hash

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC3253/2023#11]
Hola! no me queda claro aún si debemos considerar una función de hash arbitraria sin suponer nada de su naturaleza o podemos hacer una suposición sobre ella.

Gracias!

**Comment by marceloarenassaavedra** [comment]
Lo único que puedes suponer en la pregunta 4 es que existe una función de hash ``(Gen', h')`` que es resistente a preimagen.

Saludos!
