### ISSUE TITLE
Mensajes a decriptar

### ISSUE THREAD

**Issue by vicerc** [IIC3253/2023#12]
Hola! Aún no suben los mensajes a decriptar a mi repo y lo creé hace más de 24 horas.

**Comment by vicerc** [comment]
ahora los subieron, pero me sale el número de alumno de alguien más, da lo mismo?

**Comment by marceloarenassaavedra** [comment]
Sí, puedes usar los mensajes que dejamos en tu repositorio.

Saludos!
