### ISSUE TITLE
[T1P3] Se puede suponer que Gen es distribución uniforme?

### ISSUE THREAD

**Issue by gustavo-toro** [IIC3253/2023#13]
Hola, en la definición del juego de PRP, si b es 0 el verificador elige una clave k con distribución Gen. Para la pregunta 3, se puede asumir que Gen es la distribución uniforme?

Gracias.

**Comment by marceloarenassaavedra** [comment]
Sí, Gen corresponde en este caso a la distribución de las llaves para OTP, y esta es la distribución uniforme.

Saludos!

**Comment by gustavo-toro** [comment]
Muchas gracias.
