### ISSUE TITLE
librerías pregunta 1

### ISSUE THREAD

**Issue by Tiinmarr** [IIC3253/2023#15]
Hola, me gustaría saber si puedo utilizar las siguientes librerías para la pregunta 1: 
- pycryptodome
- gmpy2

**Comment by marceloarenassaavedra** [comment]
No puedes usar estas librerías para la pregunta 1. La solución de esta pregunta solo requiere de las librerías básicas de Pyhton.

Saludos!

**Comment by vWing7** [comment]
Hola, también repecto a las librerias, puedo usar funciones de la libreria math de python?

Gracias

**Comment by marceloarenassaavedra** [comment]
Sí, puedes usar funciones de la librería math de Python.

Saludos!
