### ISSUE TITLE
librerias pregunta 2

### ISSUE THREAD

**Issue by Coolgatty** [IIC3253/2023#16]
Hola, quisiera saber si debemos usar unicamente las librerias del enunciado. Es decir, debemos desarrollar todos los calculos para RSA desde 0?

**Comment by mugartec** [comment]
Hola @Coolgatty. Así es, deben desarrollar los cálculos para RSA. Si hay alguna parte que se vea demasiado compleja o que no se entienda bien por favor me cuentas.

**Comment by vWing7** [comment]
Hola, se puede usar la librería json?

Gracias

**Comment by marceloarenassaavedra** [comment]
No se puede usar la librería json.

Saludos!
