### ISSUE TITLE
Enunciado pregunta 2

### ISSUE THREAD

**Issue by Coolgatty** [IIC3253/2023#17]
Hola, queria saber como sabremos cual algoritmo tenemos que validar para la p2? O simplemente validamos con ambos algoritmos y vemos si alguno de ellos es valido? Un poco de detalle en esto porfavor

**Comment by marceloarenassaavedra** [comment]
El algoritmo que tienes que utilizar para la validación viene en el JWT. En el siguiente ejemplo sacado desde [jwt.io](https://jwt.io/) puedes ver que al traducir un JWT en texto, lo primero que aparece en el header es ``"alg": "HS256"`` indicando cuál es el algoritmo que se debe usar para la verificación:

![Sin título](https://github.com/IIC3253/2023/assets/9660300/adbe66e7-5f25-4c5b-a091-cbcdd0389b0c)

Saludos!
