### ISSUE TITLE
Formato llave publica RSA

### ISSUE THREAD

**Issue by albertoar1** [IIC3253/2023#18]
Buscando el formato PKCS #8 parece ser para llave privada no para llave pública, por lo tanto la llave pública no puede estar en ese formato.
Entonces cuál es el formato que sigue la llave pública?

**Comment by mugartec** [comment]
Toda la razón, el formato está especificado en PKCS#1. [Aquí el RFC](https://www.rfc-editor.org/rfc/rfc8017). Alguien se la juega con un PR cambiando el enunciado?

**Comment by marceloarenassaavedra** [comment]
Yo ya me la jugué con con un PR cambiando el enunciado de la pregunta 2 :) Además, hice una aclaración en la pregunta 1.

Saludos!

**Comment by Coolgatty** [comment]
> Yo ya me la jugué con con un PR cambiando el enunciado de la pregunta 2 :) Además, hice una aclaración en la pregunta 1.
> 
> Saludos!

Hola, es posible dar mas plazo debido a este cambio? Estuve dos semanas sin entender por que habia que usar PKCS#8 y fue puro tiempo perdido :/
