### ISSUE TITLE
P1 a)

### ISSUE THREAD

**Issue by drcid98** [IIC3253/2023#19]
En la pregunta 1 a se nos entrega la clase y diferentes métodos de ésta, pero a pesar de que se pide para la clase  ``Reciever`` la capacidad de generar una clave secreta, no se incluye un método para esto. Es válido crear nuestros propios métodos?

**Comment by marceloarenassaavedra** [comment]
Sí, pueden agregar sus propios métodos. Lo que no pueden hacer es cambiar los parámetros de los métodos que son dados en el jupyter notebook, ni eliminarlos, ya que serán usados para probar sus implementaciones.

Saludos!
