### ISSUE TITLE
Definiciones para la pregunta 4

### ISSUE THREAD

**Issue by albertoar1** [IIC3253/2023#2]
En la pregunta 4 de la tarea se espera que para la resistencia a pre-imagen sea muy complejo encontrar cualquier $m$ o solo debe ser muy complejo encontrar el $m_0$ utilizado para obtener $x$?

**Comment by marceloarenassaavedra** [comment]
En la pregunta 4 deben usar la definición de resistencia a preimagen dada en la [ayudantía](https://github.com/IIC3253/2023/blob/main/ayudantias/IIC3253_2023_Ayudantia3-solucion.pdf).

Saludos!

**Comment by milosoria** [comment]
Hola! Basta con dar un contraejemplo o es necesario realizar una demostración formal?

**Comment by marceloarenassaavedra** [comment]
En la pregunta 4 tiene que construir la función de hash ``(Gen, h)``, demostrar formalmente que es resistente a preimagen y demostrar formalmente que no es resistente a colisiones.

Saludos!
