### ISSUE TITLE
[T2] P2. Librerías ¿externas?

### ISSUE THREAD

**Issue by AlfreMK** [IIC3253/2023#20]
Hola, cuando se refieren a que no se pueden usar librerías externas, esto quiere decir que está permitido usar todos los módulos de la `standard library` de Python? (Es decir, todas los módulos que vienen por defecto con python como random, math, os, sys, etc)
(Véase la librería en el siguiente enlace: [https://docs.python.org/3/library/](https://docs.python.org/3/library/)

Notar que librerías de la standard library incluyen:
- json
- hmac
- hashlib
- base64

La pregunta viene principalmente por el uso de `hmac` y `json`. Que son las librerías de las cuales tengo duda si es que su uso está permitido.

Sea cual sea la respuesta, saludos y gracias de antemano

**Comment by marceloarenassaavedra** [comment]
En esta pregunta sólo se puede  importar las siguientes librerías externas:

``from hashlib import sha256``
``from base64 import urlsafe_b64decode, urlsafe_b64encode``

De esta forma, no se puede importar ``hmac`` ni ``json``, y ustedes tienen que implementar ``HMAC-SHA256``.

Saludos!
