### ISSUE TITLE
P2 RSA

### ISSUE THREAD

**Issue by Coolgatty** [IIC3253/2023#21]
Tengo que implementar un parser ASN.1 o me estoy complicando mucho? Si hay que implementarlo; hay alguna garantia sobre la complejidad de esta estructura? (siesque no hay anidaciones o cosas asi)

**Comment by mugartec** [comment]
No es necesario implementar un parser general de ASN.1, simplemente necesitas ser capaz de sacar el `d` y `N` en base a una llave secreta de tipo RSA que está en un formato especificado en ASN.1. Es un problema bastante más acotado, varias personas ya lo han logrado. Recuerda que no hay ningún problema con conversarlo y pedirle ayuda a tus compañeros :ok_hand:
