### ISSUE TITLE
[T2] P2

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC3253/2023#22]
Hola!! la verdad estoy un poco perdido con lo que tengo que hacer en la P2, ya logré obtener el N y el e de la llave pública y sé que hay que implementar HMACSHA256, pero para qué sirve haber sacado N y e. Siento que me estoy complicando mucho y estos parametros me deben servir para algo más. Muchas gracias de antemano

**Comment by mugartec** [comment]
Hola! El $N$ y el $e$ los necesitas para verificar que la firma sea váda en caso de que el JWT sea de tipo RS256. En ese caso, la firma es algo como $(SHA256(m))^d\mod N$, donde $m$ es el "mensaje" que se firma.

**Comment by SebaHagedorn** [comment]
Me quedó mas claro. Gracias!

**Comment by raimundomartinez** [comment]
Tengo una duda. Al aplicar SHA256(m), ¿se refiere a aplicar ese hash para cada byte de m individualmente, o al total del mensaje hacerle un único hash?
