### ISSUE TITLE
[T2P2] Validación de firma RS256

### ISSUE THREAD

**Issue by nbarriav** [IIC3253/2023#24]
Hola, 
Pude obtener e y N pero al verificar la clave con el hash del mensaje me entregan valores distintos.
Genere claves pública y privada para ver si mi error estaba en la obtención del e y el N pero eso estaba bien.
Teniendo (h y p en base 64, no el texto plano):
 f = hash(h.p)^d mod N, tendríamos que f es la firma que viene en el token
Obtuve e y N para luego:
f^e mod N
Con lo anterior debería obtener el hash del mensaje (es decir, hash(h.p)) pero no lo estoy logrando. Quería saber si estaba bien el enfoque que le estaba dando o va por otro lado

**Comment by mugartec** [comment]
El enfoque es el correcto. La firma de un mensaje $m$ (en este caso $h.p$ en b64) es $f = hash(m)^d \mod N$. Por lo tanto lo que esperamos es que $f^e \mod N = hash(m)^{d\cdot e} \mod N = hash(m) \mod N$. Si puedes dar un ejemplo de un JWT, la llave pública, cuales son tu $e$ y tu $N$, y qué valor estás obteniendo al sacar $f^e \mod N$ (y cómo estás transformando $f$ a un número), podemos revisarlo con más detalle.
