### ISSUE TITLE
T2P2 Importar sys

### ISSUE THREAD

**Issue by JuaniAndres** [IIC3253/2023#25]
Hola podemos importar sys para obtener el byteorder del computador que ejecuta el código, es para transformar correctamente bytes a numero entero en cualquier caso

**Comment by mugartec** [comment]
No debiese ser necesario, para transformar bytes a número enteros puedes usar int.from_bytes, y el *endianness* no debiese depender del computador. Si estoy equivocado por favor cuéntame.

**Comment by JuaniAndres** [comment]
Si es que ese mismo método requiere especificar el order que generalmente es "big", por el momento lo tengo fijo en eso pero si no me equivoco hay un grupo pequeño de computadores que por procesador ocupan "little". Preguntaba para que mi código no tuviera problemas en esos casos pero igual tampoco es tan necesario.

**Comment by JuaniAndres** [comment]
Investigando más el método int.from_bytes desde python 3.11 tiene por default el byteorder pero se supone que la tarea se revisara con python 3.10

**Comment by mugartec** [comment]
Si llega a haber un problema y es por el byteorder de `int.from_bytes` lo revisamos en la recorrección, si funciona bien en tu computador no bajará la nota.
