### ISSUE TITLE
[T2P2] Formato de JWT/llaves

### ISSUE THREAD

**Issue by lewebe** [IIC3253/2023#26]
Hola! Podemos asumir que siempre se nos van a dar pares de JWT y llaves con formatos validos? Por ejemplo, si nos pasan un JWT en RS256 y una llave publica, que la llave publica tendrá un largo divisible por 4 para poder decodificarla en base 64. O tenemos que parsear todo lo que nos llega y atrapar esos errores devolviéndolos como "False"?
Gracias!

**Comment by mugartec** [comment]
Pueden suponer que los inputs son siempre válidos, incluso que el tipo de la llave siempre corresponde al tipo del JWT.
