### ISSUE TITLE
Problema GitHub

### ISSUE THREAD

**Issue by Tiinmarr** [IIC3253/2023#27]
¿Alguien más tiene el problema de que no pueden "push" a su directorio?

**Comment by LucasCasanueva** [comment]
Hola, pudiste solucionarlo? Estoy con el mismo problema.

**Comment by Tiinmarr** [comment]
El ayudante envió un mail para que puedes crearte un nuevo repositorio ya que GitHub Classroom no permite push después de la feche de entrega
