### ISSUE TITLE
T2-P1 #BIT(n)

### ISSUE THREAD

**Issue by StroveLight** [IIC3253/2023#28]
El enunciado no define muy específicamente cómo se comporta #BIT(n).

Significa que es la menor cantidad de bits de n tal que se pueda representar n?

Es decir, es tal que cuando n no es 0, siempre el primer bit de n sea 1?

**Comment by marceloarenassaavedra** [comment]
Si un número ``n`` es distinto de ``0``, entonces en su representación binaria el bit más significativo es ``1``. La función ``#BIT(n)`` se define como el número de bits en esta representación.

Saludos!
