### ISSUE TITLE
Pregunta 1, forma de sacar la llave

### ISSUE THREAD

**Issue by yuwet15** [IIC3253/2023#3]
Hola! me surgió una duda, podemos utilizar los métodos que queramos para tratar de descifrar la llave? así tipo si ya descifré parte de la llave, y mas o menos puedo completar el resto del mensaje, el resto de llave puedo completarlo mas o menos "a mano"?

**Comment by marceloarenassaavedra** [comment]
Sí, puedes utilizar los métodos que quieras para descifrar la llave. Piensa que estás en un escenario donde interceptas una comunicación y necesitas descifrarla, por supuesto vas a usar todos los medios a tu alcance aunque no sean los más elegantes o generales.

Saludos!
