### ISSUE TITLE
[Pregunta 1] archivos cifrados

### ISSUE THREAD

**Issue by AlfreMK** [IIC3253/2023#5]
Hola, no me quedó claro si hay que dejar los archivos cifrados o eliminarlos del repositorio, por un lado me hace sentido que permanezcan en el repositorio pues servirán para la corrección, sin embargo, dado el diagrama del enunciado:
![image](https://user-images.githubusercontent.com/62082450/230701239-8be609f8-e611-4a36-abf2-a6b6b3c0d617.png)
entiendo que debemos eliminarlos o ponerlos en el .gitignore.

Solo para confirmar ¿Es esto último correcto?

**Comment by sufigueroa** [comment]
Holaa!! Cambie el enunciado para que los incluya :)
