### ISSUE TITLE
Problema con google forms

### ISSUE THREAD

**Issue by chris-gou** [IIC3253/2023#6]
Hola, tengo un problema con abrir el link del formulario para la llave, necesito permiso para abrirlo. Soy estudiante de intercambio y no he logrado conectar mi correo con gmail, por el momento solo tengo acceso al outlook. Creo que por eso no puedo abrir el formulario, sería posible cambiar los permisos?

Gracias

**Comment by sufigueroa** [comment]
Holaa!! Ya cambie los permisos :)

**Comment by chris-gou** [comment]
Gracias :)
