### ISSUE TITLE
[T1P1] Supuestos de lo que está cifrado

### ISSUE THREAD

**Issue by StroveLight** [IIC3253/2023#7]
Hola, solo deseo saber si se pueden suponer las siguientes cosas de lo que está cifrado con el fin de no alargar innecesariamente el código:
1. Todos los textos decriptados están en solo un idioma
2. Todos los textos decriptados están en español
3. El encoding de los archivos decriptados es siempre el mismo
4. El encoding de los archivos decriptados es utf-8
5. Los textos decriptados corresponden a una frase/oración que no está cortada ni al inicio ni al final
6. Todas las palabras están o capitalizadas o en minúscula

**Comment by marceloarenassaavedra** [comment]
Para resolver el problema la única información que tienes es que se usó OTP de una forma no adecuada, lo que se traduce en que una misma clave fue usada varias veces.

En todo caso tiene sentido lo que planteas al tratar de quebrar el código, es útil hacer algunos supuestos que puedan ayudar a reducir el espacio de búsqueda. Pero si esos supuestos no funcionan, hay que hacer otros, que es finalmente lo que pasa en una situación real donde alguien está tratando de romper un código.

Saludos!
