### ISSUE TITLE
[T1] Links en el enunciado

### ISSUE THREAD

**Issue by jerrazuriz99** [IIC3253/2023#8]
Hola, el pdf del enunciado no me muestra ningún link praa acceder al from a al repositorio personal
, que puedo hacer? 
![Captura de Pantalla 2023-04-15 a la(s) 12 07 21](https://user-images.githubusercontent.com/53884268/232237681-32b444be-59d5-4ac0-8083-40e6a7e1075d.png)

**Comment by sufigueroa** [comment]
Holaa! Los links no funcionan desde github, debes descargar el archivo/clonar el repositorio :)
